backend:
  name: github
  repo: Fptbb/Blog-Do-Fp
  branch: master
  site_domain: optimistic-varahamihira-edaf78.netlify.app

media_folder: 'src/images'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{fields.path}}'
    path: '{{slug}}/index'
    fields:
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          default: ['aleatorio', 'projetos', 'programacao'],
        }
      - { label: 'Data', name: 'date', widget: 'datetime' }
      - { label: 'Path', name: 'path', widget: 'string', default: 'NomeDoPost' }
      - {
          label: 'Cover',
          name: 'cover',
          widget: 'image',
          default: '/src/images/preview.png',
        }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
